spring:
  data:
    redis:
      host: localhost
      database: 3
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
#            instanceName: spring-boot-quartz
            instanceId: AUTO #默认主机名和时间戳生成实例ID,可以是任何字符串，但对于所有调度程序来说，必须是唯一的 对应qrtz_scheduler_state INSTANCE_NAME字段
          jobStore:
#            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore #持久化配置
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
          threadPool:
            threadCount: 10
            threadsInheritContextClassLoaderOfInitializingThread: true


mybatis-flex:
  global-config:
    print-banner: false
    logic-delete-column: deleted
  datasource:
    ds1:
      url: jdbc:mysql://localhost:3306/luna
      username: root
      password: Passw0rd
#      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        connection-test-query: SELECT 1
    ds2:
      url: jdbc:mysql://127.0.0.1:3306/tauren
      username: root
      password: Passw0rd
#      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        connection-test-query: SELECT 1
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
logging:
  level:
    web: debug # Web 模块日志级别
    org.springframework.web: DEBUG  # Spring Web 框架日志
    org.springframework.boot.web.servlet: DEBUG  # Servlet 容器日志
    org.springframework.security: DEBUG
jwt:
  expiration: 28800000
#  refreshExpirationMs: 86400000