server:
  port: 8086
spring:
  data:
    redis:
      host: 172.16.2.15
      database: 3
      password: 3eCrAw8Ba6Tg
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
#            instanceName: spring-boot-quartz
            instanceId: AUTO #默认主机名和时间戳生成实例ID,可以是任何字符串，但对于所有调度程序来说，必须是唯一的 对应qrtz_scheduler_state INSTANCE_NAME字段
          jobStore:
#            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore #持久化配置
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
          threadPool:
            threadCount: 10
            threadsInheritContextClassLoaderOfInitializingThread: true


mybatis-flex:
  global-config:
    print-banner: false
    logic-delete-column: deleted
  datasource:
    ds1:
      url: jdbc:mysql://172.16.2.15:3306/luna
      username: root
      password: Zkah@83539595S
#      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        connection-test-query: SELECT 1
    ds2:
      url: jdbc:mysql://172.16.2.15:3306/nmfm_mine
      username: root
      password: Zkah@83539595S
#      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        connection-test-query: SELECT 1
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
logging:
  level:
    web: INFO # Web 模块日志级别
    org.springframework.web: INFO  # Spring Web 框架日志
    org.springframework.boot.web.servlet: INFO  # Servlet 容器日志
    org.springframework.security: INFO
jwt:
  expiration: 28800000
#  refreshExpirationMs: 86400000